package frc.robot.beaverlib.odometry

import edu.wpi.first.apriltag.AprilTagFieldLayout
import edu.wpi.first.math.geometry.Pose2d
import edu.wpi.first.math.geometry.Pose3d
import edu.wpi.first.math.geometry.Transform3d
import org.photonvision.PhotonCamera
import org.photonvision.PhotonPoseEstimator
import org.photonvision.targeting.PhotonPipelineResult

/**
 * A class that represents a Photonvision camera
 * @param name The cameras name, as it appears in PhotonVision
 * @param robotToCamera The translation vector from the camera to the center of the robot
 * @param strategy The primary pose estimation strategy this camera should use
 * @param fallbackStrategy The secondary pose estimation this camera should use if [strategy] is not possible. (Will not be set if null)
 */
class BeaverVisionCamera(val name: String, val robotToCamera: Transform3d, layout: AprilTagFieldLayout, strategy: PhotonPoseEstimator.PoseStrategy, fallbackStrategy : PhotonPoseEstimator.PoseStrategy? = null ) {
    val cam = PhotonCamera(name)
    /** Gets all unread results (SHOULD ONLY BE USED BY BEAVERPHOTONVISION) */
    val results: List<PhotonPipelineResult> get() = cam.allUnreadResults
    /** The pose estimator for this camera */
    val poseEstimator = PhotonPoseEstimator(layout, strategy, robotToCamera)

    init {
        if(fallbackStrategy != null) poseEstimator.setMultiTagFallbackStrategy(fallbackStrategy)
    }

    /** Returns an estimated Pose3d given a PhotonPipelineResult (That should have been generated by this camera) */
    fun getEstimatedRobotPose(result: PhotonPipelineResult) : Pose3d? {
        val estimatedPose = poseEstimator.update(result) ?: return null
        if (estimatedPose.isEmpty) return null
        return estimatedPose.get().estimatedPose
    }
    fun setReference(pose: Pose2d) { poseEstimator.setReferencePose(pose) }
}